typography_spectrum: 0.46946
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.10501
analytics:
  google: UA-57879473-1
  facebook: null
  twitter: null
name: Skylinelady
cta:
  domain: null
  bucket: null
  version: null
favicon: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: Travel & Lifestyle
purpose: []
